#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import time
import traceback

from listener import utils
from listener.auth import get_auth_handler
from listener.controller import TwitterListener, TwitterStream
from tweepy.error import TweepError


def start_daemon():
    """
    Starting Listener Daemon.
    """
    while True:
        try:
            auth = get_auth_handler()
            listener = TwitterListener(auth=auth)
            twitter_stream = TwitterStream(auth, listener)
        except Exception as error:
            msg = [traceback.format_exc()]
            if isinstance(error, TweepError):
                msg.append(error.reason)
            msg.append('An error occurred. Restarting listener...')
            utils.message(body='\n\n'.join(msg))
            time.sleep(2)


if __name__ == '__main__':
    start_daemon()
